input-output-hk/ouroboros-leios

.github/workflows/ci.yaml
.gitignore
Logbook.md
flake.lock
flake.nix
formal-spec/CategoricalCrypto.agda
formal-spec/Leios/Network.agda
formal-spec/Leios/SimpleSpec.agda
formal-spec/leios-spec.agda-lib
nix/agda.nix
nix/outputs.nix
nix/shell.nix

Currently this relies on a bunch of ledger code to get started quickly. The plan is to factor this stuff out into libraries later.

Add WIP simple Leios spec

---

README.md
flake.lock
flake.nix
nix/agda.nix

Pinned agda version to 2.6.4.3.

---

delta_q/Cargo.lock
delta_q/Cargo.toml
delta_q/README.md
delta_q/index.html
delta_q/models.txt
delta_q/src/agent.rs
delta_q/src/bin/editor-web.rs
delta_q/src/cdf.rs
delta_q/src/delta_q.rs
delta_q/src/lib.rs
delta_q/src/outcome.rs
delta_q/src/parser.rs
delta_q/src/render.rs
delta_q/src/step_function.rs
delta_q/styles.css

This implements an extension to the theory, described in the README. If you want to play with it,
feel free to load the latest set of formulas from models.txt in the web app.
This does not yet fix issue #41 as the computed load outcomes have not yet been validated against
reality nor simulation.

add load analysis to ΔQ tool

---

formal-spec/Leios/Base.agda
formal-spec/Leios/SimpleSpec.agda

__Base chain__ rules from Figure 2: The Simplified Leios Protocol

Formal specification: Base chain

---

formal-spec/Leios/Abstract.agda
formal-spec/Leios/Base.agda
formal-spec/Leios/Blocks.agda
formal-spec/Leios/FFD.agda
formal-spec/Leios/KeyRegistration.agda
formal-spec/Leios/SimpleSpec.agda
formal-spec/Leios/VRF.agda
formal-spec/Leios/Voting.agda

* Moved types that are consumed by a `functionality` to the respective modules
* Updating the `LeisosState` upon receiving a message from `FFD`
* Resolved `postulates`

Formal specification: Message fetching

---

Logbook.md
analysis/Cardano-Throughput.InsightMaker

The system-dynamics simulation of Cardano throughput was enhanced and checked.
- Documented all variables.
- Adjusted slider ranges.
- Added constraint for valid ranges of variables.
- Tested scenarios.
- Checked equations.
- Fixed extreme scenario were funds flow into reserve.
- Created [tutorial video](https://drive.google.com/file/d/1YrQLLsgsPt4XHa707c-CfTLkivKRyaa0/view?usp=sharing)
- Published [version 0.2](https://www.insightmaker.com/insight/5B3Sq5gsrcGzTD11GyZJ0u/Cardano-Throughput-v0-2) of the model.

Revisions to throughput cost model

---

formal-spec/Leios/Short.lagda.md

Convert Short-Pipeline Leios module to literate Agda

Literate Agda

---

site/news/2024-12-09-weekly-progress-summary.md
site/news/2024-12-16-weekly-progress-summary.md
site/news/2024-12-23-weekly-progress-summary.md
site/news/2024-12-30-weekly-progress-summary.md
site/news/2025-01-06-weekly-progress-summary.md

This PR suggests copy improvements to align with the IO style guide. This might include:
- Grammar edits
- Formatting tweaks (the use of single quotation marks, no full stops after each bullet point (only after the last item), the use of 'Sentence case titles', punctuation (eg, the use of en dashes), etc
- Style edits (clarified acronyms, avoiding overcapitalization, etc)

Tech writing review

---

site/news/2025-01-13-weekly-progress-summary.md

@olgahryniuk please have a look.

docs: logbook weekly update

---

site/docs/development/cost-estimator.md
site/docs/development/overview.md
site/docs/development/throughput-simulation.md

This first commit adds a link to the weekly updates page.

Minor edits to the R&D section

---

site/news/2025-03-03-weekly-progress-summary.md

Weekly progress summary for the period 2025-03-03 to 2025-03-10

Weekly Update 2025-03-03

---

site/news/2025-03-10-weekly-progress-summary.md

Weekly progress summary for the period 2025-03-10 to 2025-03-17

Weekly Update 2025-03-10

---

site/news/2025-04-07-weekly-progress-summary.md

Weekly progress summary for the period 2025-04-07 to 2025-04-14

Weekly Update 2025-04-07

---

flake.lock
flake.nix
leios-trace-verifier/Parser.agda

Lotteries need to be built from the trace log, as they are not deterministic

trace-verifier: lotteries built from trace

---

.github/workflows/conformance.yaml
leios-trace-verifier/hs-src/app/Main.hs

Failed traces return non-zero exit code.

Meaningful exit code for `leios-trace-verifier`

---

.github/workflows/simulation.yaml
leios-trace-hs/src/LeiosConfig.hs

Updated config embedded in haskell

---

docs/cddl/diffs/common/input-blocks.md
docs/cddl/diffs/full-sharding/README.md
docs/cddl/diffs/full-sharding/input-blocks.md
docs/cddl/diffs/full-sharding/reward-account.md
docs/cddl/diffs/full-sharding/utxo.md
docs/cddl/diffs/over-collateralization/transactions.md

**Sharded Design**
**Over-collateralized**

Ledger Design CDDL (Over-collateralized & Sharded Reward Account)

---

simulation/docs/SimulatorModel.md

I'm writing notes that I found useful when trying to onboard myself to the simulator.
In that light, it's clear that these might be wrong at this stage, but that's true of any comment, and they'll be helpful in the mean-time.
Edit: this PR pivoted before being merged; see my top-level comment on 2025 June 25 below.

Explain state variables in Haskell SimulatorModel.md

---

docs/cip/README.md

- Wrote a few paragraphs on "Why this protocol variant" including why higher latency and high concurrency give rise to problems
- Moved the bottom line formula to rationale
- Added the argument of solving chain growth before increasing capacity further
- Re-ordered sections as proposed by @will-break-it (and merged the duplicates we had in the end of the rationale chapter)
- I like the paragraphs that got added in the meantime and we should incorporate them somehow

CIP Rationale: why this protocol variant & concurrency

---

sim-rs/CHANGELOG.md
sim-rs/Cargo.lock
sim-rs/implementations/LINEAR_LEIOS.md
sim-rs/sim-cli/Cargo.toml
sim-rs/sim-core/Cargo.toml
sim-rs/sim-core/src/model.rs
sim-rs/sim-core/src/sim/linear_leios.rs

- Update dependencies to fix vulnerability
- Apply RB/EB validation CPU time when generating new RB/EBs.
- Only vote for EBs if their RB was received within `Δ_header` of its production.

Sim rs 1.1
