input-output-hk/ouroboros-leios

delta_q/Cargo.lock, delta_q/Cargo.toml, delta_q/README.md, delta_q/src/bin/editor-web.rs, delta_q/src/bin/editor.rs, delta_q/src/cdf.rs, delta_q/src/delta_q.rs, delta_q/src/lib.rs, delta_q/src/parser.rs, delta_q/src/render.rs, delta_q/styles.css
- optimise representation of CDFs
- add printing and parsing for CDFs and ΔQ expressions
- make expressions textually editable in the UI
- add recursion (a.k.a. exponentiation) operator
=> more work on Rust-based ΔQ

simulation/src/Main.hs, simulation/src/ModelTCP.hs, simulation/src/P2P.hs, simulation/src/RelayProtocol.hs, simulation/src/SimRelay.hs, simulation/src/Viz.hs, simulation/src/VizChart.hs, simulation/src/VizSimRelay.hs, simulation/src/VizSimRelayP2P.hs, simulation/src/VizSimTCP.hs
Our [coding standards]() requires code to be formatted using fourmolu and the `fourmolu.yaml` file provided at the toplevel of the directory. This PR is the result of running `fourmolu -i .` in the `simulation` directory.
=> Format simulation code using fourmolu

cabal.project, simulation/README.md, simulation/ouroboros-leios-sim.cabal, simulation/src/Main.hs, simulation/src/VizName.hs, simulation/test/Main.hs, simulation/test/VizNameSpec.hs
Also provide a `run` command to, well, run the simulation and rename some types to use less abbreviations.
=> Provide a `list` command to list available visualisations

sim-rs/Cargo.lock, sim-rs/sim-cli/Cargo.toml, sim-rs/sim-cli/src/events.rs, sim-rs/sim-core/src/clock.rs, sim-rs/sim-core/src/config.rs, sim-rs/sim-core/src/events.rs, sim-rs/sim-core/src/model.rs, sim-rs/sim-core/src/sim.rs, sim-rs/test_data/realistic.toml, sim-rs/test_data/simple.toml
Restructured the sim's event output based on the wasm experiment; events are now more uniform and less redundant.
Implemented basic sharding across IBs. The sim now outputs the mean+stddev of the time it took for a transaction to reach a block, to help understand the effect on latency
=> 2024 10 24/sim rs

sim-rs/sim-cli/src/events.rs, sim-rs/sim-core/src/events.rs, sim-rs/sim-core/src/model.rs, sim-rs/sim-core/src/network.rs, sim-rs/sim-core/src/sim.rs, sim-rs/sim-core/src/sim/event_queue.rs, sim-rs/sim-core/src/sim/node.rs
Make every node run in its own separate tokio task. This lets the simulation run using as many threads as possible.
=> Multithread sim

sim-rs/Cargo.lock, sim-rs/sim-cli/Cargo.toml, sim-rs/sim-cli/src/events.rs, sim-rs/sim-core/src/clock.rs, sim-rs/sim-core/src/config.rs, sim-rs/sim-core/src/network.rs, sim-rs/sim-core/src/sim.rs, sim-rs/sim-core/src/sim/node.rs, sim-rs/test_data/realistic.toml
This lets the rust program simulate TX/IB propagation in realtime at 100x current transaction volume, and in 25% of realtime at 1000x current transaction volume.
Senders each hold one channel per receiver they communicate with, and receivers pull from those channels on demand. This lets us avoid maintaining a centralized core or running a background thread to forward messages to the right nodes.
Every receiver tracks a VecDeque of incoming messages per sender. In the `recv` method, the receiver just needs to compare the first elements of each VecDeque to decide what to return.
=> Replace netsim with a decentralized network layer

formal-spec/Leios/Abstract.agda, formal-spec/Leios/Base.agda, formal-spec/Leios/Blocks.agda, formal-spec/Leios/FFD.agda, formal-spec/Leios/Prelude.agda, formal-spec/Leios/SimpleSpec.agda, formal-spec/Leios/VRF.agda
It took me 3 attempts with a whole bunch of complicated things until I realized that we can just do it like that. It's a little annoying that we now have to actually use instance resolution for types that are fully known, but I think it ticks all the boxes: 
- we can instantiate it however we like whenever we like (in particular we don't have to use GHC pragmas, which means we can offer a library and the user of the library can provide hashing capabilities)
- it doesn't clutter the spec beyond some paint threshold
=> Replace hashing postulates with type classes

simulation/src/PraosProtocol/BlockFetch.hs, simulation/src/PraosProtocol/BlockGeneration.hs, simulation/src/PraosProtocol/ChainSync.hs, simulation/src/PraosProtocol/Common.hs, simulation/src/PraosProtocol/ExamplesPraosP2P.hs, simulation/src/PraosProtocol/PraosNode.hs, simulation/src/PraosProtocol/SimBlockFetch.hs, simulation/src/PraosProtocol/SimChainSync.hs, simulation/src/PraosProtocol/SimPraos.hs, simulation/src/PraosProtocol/VizSimPraos.hs
- Added header validation delay
- Refined chain order with hash of tip, eliminates diffusion latency outliers
=> Some Praos sim fixes

formal-spec/Leios/SimpleSpec.agda
We want to ensure that the `Slot` rule only fires if all our block production duties are completed. To do this, I've added a set that keeps track of these to the state and adjusted the rules so that they can only fire one per slot. Then, `Slot` checks that all duties are indeed completed. This means that if we can't produce anything, we still need to update the state to not get stuck, which is why there are now negative versions of some rules.
While doing this, I noticed that we're not keeping the state of the base chain in our state and instead always universally quantifying over all those states. I fixed that too.
=> Add a `SlotUpkeep` type to enforce dependencies between rules

simulation/ouroboros-leios-sim.cabal, simulation/src/LeiosProtocol/Short/Node.hs, simulation/src/LeiosProtocol/Short/SimP2P.hs, simulation/src/LeiosProtocol/Short/VizSim.hs, simulation/src/LeiosProtocol/Short/VizSimP2P.hs, simulation/src/LeiosProtocol/TaskMultiQueue.hs, simulation/src/Main.hs, simulation/src/WorkerPool.hs
* Added rather crude chart to show number of cores used per node.
* TODO: moving average might be more illustrative.
* Added `-N` flag to control parallelism, accepts 'unbounded' or number of cores.
* `cabal run ols -- viz short-leios-p2p-1 -N unbounded` shows a node using 13 cores around 30s.
* Otherwise things seem to get busy around votes, though maybe less so as time goes on?
=> Bounded parallelism and CPU Cores usage chart

.github/workflows/ci.yaml
=> ci: only run ci for relevant changes

simulation/src/ChanDriver.hs, simulation/src/LeiosProtocol/Short/VizSim.hs, simulation/src/Topology.hs
* Some trickery with named fields. Fixed by an explict type signature.
* Unused type extensions.
* New library type aliases
=> Fix build with ghc-9.6.x

site/src/pages/index.module.css, site/src/pages/index.tsx
Added a new section to the landing page that embeds a simulation video demonstrating the Leios protocol in action.
- Added VideoSection component to index.tsx
- Added corresponding styles in index.module.css
- Video is embedded from Google Drive for easier maintenance
- Added visual separation between Features and Video sections
1. Clone the repository
2. Navigate to the site directory:
```bash
cd site
```
3. Install dependencies:
```bash
yarn install
```
4. Start the development server:
```bash
yarn start
```
5. Open http://localhost:3000 in your browser
6. Scroll down past the Features section to see the new Video section
The video is embedded from Google Drive. Make sure you have internet access to view it.
=> site(sim): add haskell short-leios simulation video to landing page

.hlint.yaml
I realized hlint was causing me unneeded friction, so figured I would tailor the config to its intended purpose.
=> simulation: make hlint report only about restricted modules

delta_q/src/compaction.rs, delta_q/src/step_function.rs
If we create a CDF with multiple points at the same X value, only the highest Y for each X is relevant.
=> delta-q: handle redundant x values in compact

site/docs/how-it-works.md, site/docs/overview.md, site/docs/protocol-overview.md, site/docs/resources.md
Add a CTA sentence to learn more
=> Minor copy adjustments

simulation/src/LeiosProtocol/Short.hs
=> (Fix #207) simulation: use simpler sortition for [ib|eb]-gen-probability <= 1.

data/simulation/trace.haskell.d.ts, data/simulation/trace.rust.d.ts
=> Trace Schema Changes

data/simulation/Makefile, data/simulation/example.haskell.jsonl, data/simulation/example.rust.jsonl, data/simulation/trace.haskell.d.ts, data/simulation/trace.haskell.schema.json, data/simulation/trace.rust.d.ts, data/simulation/trace.rust.schema.json
- Draft of current simulation trace schema
- Serves as base for discussed changes
=> data: add trace schema for haskell & rust

data/simulation/config.default.yaml, simulation/src/LeiosProtocol/Config.hs
During TCP's slow start phase, the congestion window (CWND) typically:
Starts with an initial congestion window (initcwnd) of 10 MSS (Maximum Segment Size)
Doubles after each round trip time (RTT)
With a standard MSS of 1460 bytes:
- Round Trip 1: 10 MSS = 10 × 1460 = 14,600 bytes
- Round Trip 2: 20 MSS = 20 × 1460 = 29,200 bytes
- Round Trip 3: 40 MSS = 40 × 1460 = 58,400 bytes
Total for 3 round trips: 14,600 + 29,200 + 58,400 = 102,200 bytes
However, we need to account for TCP/IP overhead:
- TCP header: 20 bytes
- IP header: 20 bytes
This means each segment carries 1460 bytes of payload but requires 1500 bytes on the wire.
When accounting for this overhead and some implementation variations (like initial window sizes that might be slightly different in various TCP stacks), the practical …
=> fix: optimize ib size for 3 TCP round trips

flake.lock, flake.nix, leios-trace-verifier/Parser.agda
Verify a simulation trace against the relational specification of Short Leios
=> Trace verifier

site/news/2025-03-17-weekly-progress-summary.md
Weekly progress summary for the period 2025-03-17 to 2025-03-24
=> Weekly Update 2025-03-17

site/news/2025-01-27-weekly-progress-summary.md, site/news/2025-02-03-weekly-progress-summary.md, site/news/2025-02-10-weekly-progress-summary.md, site/news/2025-02-17-weekly-progress-summary.md, site/news/2025-02-24-weekly-progress-summary.md, site/news/2025-03-03-weekly-progress-summary.md, site/news/2025-03-24-weekly-progress-summary.md
Weekly progress summary for the period 2025-03-24 to 2025-03-31
=> Weekly Update 2025-03-24

docs/workshop/day-1-recap.md, docs/workshop/day-2-recap.md, docs/workshop/day-3-recap.md, site/news/2025-03-31-weekly-progress-summary.md
Weekly progress summary for the period 2025-03-31 to 2025-04-07
=> Weekly Update 2025-03-31

site/news/2025-04-14-weekly-progress-summary.md
Weekly progress summary for the period 2025-04-14 to 2025-04-21
=> Weekly Update 2025-04-14

site/news/2025-05-12-weekly-progress-summary.md
Weekly progress summary for the period 2025-05-12 to 2025-05-19
=> Weekly Update 2025-05-12

data/simulation/config.d.ts, data/simulation/config.default.yaml, data/simulation/config.schema.json, data/simulation/example.rust.jsonl, data/simulation/trace.rust.d.ts, data/simulation/trace.rust.schema.json, sim-rs/sim-core/src/config.rs, sim-rs/sim-core/src/events.rs, sim-rs/sim-core/src/model.rs, sim-rs/sim-core/src/sim/node.rs, sim-rs/sim-core/src/sim/tx.rs
as described in https://docs.google.com/document/d/1QRt7MF5guLDapkois4v5hzHzMH8iZf1humFB38Lv8mU/edit?tab=t.0
=> Implement overcollateralization

data/simulation/trace.shared.d.ts, data/simulation/trace.shared.schema.json, leios-trace-hs/src/LeiosEvents.hs, leios-trace-verifier/Parser.agda, leios-trace-verifier/examples/valid/agda-2.jsonl, leios-trace-verifier/hs-src/test/Spec/Transition.hs, simulation/src/LeiosProtocol/Short/Sim.hs
Closes https://github.com/input-output-hk/ouroboros-leios/issues/387.
=> Add EB links to EBGenerated event

sim-rs/sim-cli/src/events.rs
This seems to be the only way to get a total sum of things that will be stored for FullWithoutIbs and FullWithTxReferences variants.
~~Open point: this will cound transaction bytes double for the other variants and worsen theire spatial efficiency while we would not store txs double of course.~~
=> Count total_leios_bytes differently

data/simulation/config.d.ts, data/simulation/config.default.yaml, data/simulation/config.schema.json, data/simulation/variants/config.linear.yaml, sim-rs/LINEAR_LEIOS.md, sim-rs/parameters/linear.yaml, sim-rs/sim-cli/src/events/liveness.rs, sim-rs/sim-core/src/config.rs, sim-rs/sim-core/src/events.rs, sim-rs/sim-core/src/model.rs, sim-rs/sim-core/src/sim.rs, sim-rs/sim-core/src/sim/driver.rs, sim-rs/sim-core/src/sim/leios.rs, sim-rs/sim-core/src/sim/linear_leios.rs, sim-rs/sim-core/src/sim/lottery.rs
See `LINEAR_LEIOS.md` for usage.
=> Linear Leios

docs/threat-model.md
This is a first sketch for a threat model as a dedicated artifact. We have another similar collection of threats here
https://github.com/input-output-hk/ouroboros-leios/blob/main/docs/technical-report-1.md#threat-model
In this document, we follow an established process of threat modeling by also describing a system overview, assets to protect and go more into detail detail on threats, prerequisites, attack vector, cost and impact.
This should be updated with more detail / reference the concrete protocol variant we propose in the CIP and accordingly with assets, threats and mitigations.
=> Create a dedicated threat model for Leios

data/simulation/config.d.ts, data/simulation/config.schema.json, sim-rs/CHANGELOG.md, sim-rs/Cargo.lock, sim-rs/implementations/LINEAR_LEIOS.md, sim-rs/sim-cli/Cargo.toml, sim-rs/sim-cli/src/main.rs, sim-rs/sim-core/Cargo.toml, sim-rs/sim-core/src/config.rs, sim-rs/sim-core/src/sim/linear_leios.rs
=> Sim rs 1.0

sim-rs/CHANGELOG.md, sim-rs/Cargo.lock, sim-rs/implementations/LINEAR_LEIOS.md, sim-rs/sim-cli/Cargo.toml, sim-rs/sim-cli/src/events.rs, sim-rs/sim-core/Cargo.toml, sim-rs/sim-core/src/clock.rs, sim-rs/sim-core/src/events.rs, sim-rs/sim-core/src/model.rs, sim-rs/sim-core/src/sim/leios.rs, sim-rs/sim-core/src/sim/linear_leios.rs, sim-rs/sim-core/src/sim/stracciatella.rs
- Respect timings according to the latest CIP draft:
- RB headers must be received within `Delta_header`
- Voting must wait until `3 * Delta_header`
- Voting must finish by `3 * Delta_header + L_vote`
- EB cannot be referenced until after `3 * Delta_header + L_vote + L_diff`
- Don't include transactions directly in an RB if it also includes an endorsement
- Don't produce empty EBs
- Fix linter warnings from newer rust version
=> Sim rs 1.3

docs/ImpactAnalysis.md
This currently covers serialization, new block structure, voting committee and protocol parameter considerations.
=> Add section about impact on ledger
